### PR TITLE
Added formatting for differential expression analysis and merged with your last commit

### PR DESCRIPTION
**Pull request by gdancik**
This is a merge of gdancik commit 1cb35aa72ba11999478c6df8f41c71b78786ad57
    with jasmine commit 399a6cbae3a55f8ec65a36befd8ef35b7c08f8bf, merging initial
    formatting of differential expression analysis with changes to the survival analysis.

    Everything is up-to-date, with the exception of stripchart2.R. Jasmine, I did not merge your latest changes to stripchart3 since that was giving me errors.

### CODE REVIEW

**Comment by jasdumas** [comment]
Great - I can't automatically merge this now, but I will work to resolve it tonight

**Comment by gdancik** [comment]
I just e-mailed you!

**Comment by jasdumas** [comment]
I have the option of reverting back to a working commit, but the only thing that is different is the stripchart2.R file? 

I can manually apply the ggplot2 changes to your code once it is merged.

**Comment by gdancik** [comment]
That's right. The code is identical to your latest commit, plus my changes, with the exception of the changes you made to the stripchart2.R file.

**Comment by jasdumas** [comment]
Okie - I'm going to make some manually adjustments to my local copy and see if that allows me to merge your commit. btw, I cloned your copy and the changes you made are fantastic!

**Comment by jasdumas** [comment]
yay that worked now! thanks

**Pull request merged**
